# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lcmservice_pb2 as lcmservice__pb2


class AppLCMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.instantiate = channel.unary_unary(
                '/lcmservice.AppLCM/instantiate',
                request_serializer=lcmservice__pb2.InstantiateRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.InstantiateResponse.FromString,
                )
        self.terminate = channel.unary_unary(
                '/lcmservice.AppLCM/terminate',
                request_serializer=lcmservice__pb2.TerminateRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.TerminateResponse.FromString,
                )
        self.query = channel.unary_unary(
                '/lcmservice.AppLCM/query',
                request_serializer=lcmservice__pb2.QueryRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.QueryResponse.FromString,
                )
        self.queryKPI = channel.unary_unary(
                '/lcmservice.AppLCM/queryKPI',
                request_serializer=lcmservice__pb2.QueryKPIRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.QueryKPIResponse.FromString,
                )
        self.queryPackage = channel.unary_unary(
                '/lcmservice.AppLCM/queryPackage',
                request_serializer=lcmservice__pb2.QueryPackageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.QueryPackageResponse.FromString,
                )
        self.uploadConfig = channel.stream_unary(
                '/lcmservice.AppLCM/uploadConfig',
                request_serializer=lcmservice__pb2.UploadCfgRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.UploadCfgResponse.FromString,
                )
        self.removeConfig = channel.unary_unary(
                '/lcmservice.AppLCM/removeConfig',
                request_serializer=lcmservice__pb2.RemoveCfgRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.RemoveCfgResponse.FromString,
                )
        self.workloadEvents = channel.unary_unary(
                '/lcmservice.AppLCM/workloadEvents',
                request_serializer=lcmservice__pb2.WorkloadEventsRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.WorkloadEventsResponse.FromString,
                )
        self.uploadPackage = channel.stream_unary(
                '/lcmservice.AppLCM/uploadPackage',
                request_serializer=lcmservice__pb2.UploadPackageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.UploadPackageResponse.FromString,
                )
        self.deletePackage = channel.unary_unary(
                '/lcmservice.AppLCM/deletePackage',
                request_serializer=lcmservice__pb2.DeletePackageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.DeletePackageResponse.FromString,
                )


class AppLCMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def instantiate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryKPI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadConfig(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def workloadEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadPackage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deletePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppLCMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'instantiate': grpc.unary_unary_rpc_method_handler(
                    servicer.instantiate,
                    request_deserializer=lcmservice__pb2.InstantiateRequest.FromString,
                    response_serializer=lcmservice__pb2.InstantiateResponse.SerializeToString,
            ),
            'terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.terminate,
                    request_deserializer=lcmservice__pb2.TerminateRequest.FromString,
                    response_serializer=lcmservice__pb2.TerminateResponse.SerializeToString,
            ),
            'query': grpc.unary_unary_rpc_method_handler(
                    servicer.query,
                    request_deserializer=lcmservice__pb2.QueryRequest.FromString,
                    response_serializer=lcmservice__pb2.QueryResponse.SerializeToString,
            ),
            'queryKPI': grpc.unary_unary_rpc_method_handler(
                    servicer.queryKPI,
                    request_deserializer=lcmservice__pb2.QueryKPIRequest.FromString,
                    response_serializer=lcmservice__pb2.QueryKPIResponse.SerializeToString,
            ),
            'queryPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.queryPackage,
                    request_deserializer=lcmservice__pb2.QueryPackageRequest.FromString,
                    response_serializer=lcmservice__pb2.QueryPackageResponse.SerializeToString,
            ),
            'uploadConfig': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadConfig,
                    request_deserializer=lcmservice__pb2.UploadCfgRequest.FromString,
                    response_serializer=lcmservice__pb2.UploadCfgResponse.SerializeToString,
            ),
            'removeConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.removeConfig,
                    request_deserializer=lcmservice__pb2.RemoveCfgRequest.FromString,
                    response_serializer=lcmservice__pb2.RemoveCfgResponse.SerializeToString,
            ),
            'workloadEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.workloadEvents,
                    request_deserializer=lcmservice__pb2.WorkloadEventsRequest.FromString,
                    response_serializer=lcmservice__pb2.WorkloadEventsResponse.SerializeToString,
            ),
            'uploadPackage': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadPackage,
                    request_deserializer=lcmservice__pb2.UploadPackageRequest.FromString,
                    response_serializer=lcmservice__pb2.UploadPackageResponse.SerializeToString,
            ),
            'deletePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.deletePackage,
                    request_deserializer=lcmservice__pb2.DeletePackageRequest.FromString,
                    response_serializer=lcmservice__pb2.DeletePackageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lcmservice.AppLCM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppLCM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def instantiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/instantiate',
            lcmservice__pb2.InstantiateRequest.SerializeToString,
            lcmservice__pb2.InstantiateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/terminate',
            lcmservice__pb2.TerminateRequest.SerializeToString,
            lcmservice__pb2.TerminateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/query',
            lcmservice__pb2.QueryRequest.SerializeToString,
            lcmservice__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryKPI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/queryKPI',
            lcmservice__pb2.QueryKPIRequest.SerializeToString,
            lcmservice__pb2.QueryKPIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/queryPackage',
            lcmservice__pb2.QueryPackageRequest.SerializeToString,
            lcmservice__pb2.QueryPackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def uploadConfig(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/lcmservice.AppLCM/uploadConfig',
            lcmservice__pb2.UploadCfgRequest.SerializeToString,
            lcmservice__pb2.UploadCfgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def removeConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/removeConfig',
            lcmservice__pb2.RemoveCfgRequest.SerializeToString,
            lcmservice__pb2.RemoveCfgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def workloadEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/workloadEvents',
            lcmservice__pb2.WorkloadEventsRequest.SerializeToString,
            lcmservice__pb2.WorkloadEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def uploadPackage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/lcmservice.AppLCM/uploadPackage',
            lcmservice__pb2.UploadPackageRequest.SerializeToString,
            lcmservice__pb2.UploadPackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deletePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.AppLCM/deletePackage',
            lcmservice__pb2.DeletePackageRequest.SerializeToString,
            lcmservice__pb2.DeletePackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class VmImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createVmImage = channel.unary_unary(
                '/lcmservice.VmImage/createVmImage',
                request_serializer=lcmservice__pb2.CreateVmImageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.CreateVmImageResponse.FromString,
                )
        self.queryVmImage = channel.unary_unary(
                '/lcmservice.VmImage/queryVmImage',
                request_serializer=lcmservice__pb2.QueryVmImageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.QueryVmImageResponse.FromString,
                )
        self.deleteVmImage = channel.unary_unary(
                '/lcmservice.VmImage/deleteVmImage',
                request_serializer=lcmservice__pb2.DeleteVmImageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.DeleteVmImageResponse.FromString,
                )
        self.downloadVmImage = channel.unary_stream(
                '/lcmservice.VmImage/downloadVmImage',
                request_serializer=lcmservice__pb2.DownloadVmImageRequest.SerializeToString,
                response_deserializer=lcmservice__pb2.DownloadVmImageResponse.FromString,
                )


class VmImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createVmImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryVmImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteVmImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def downloadVmImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VmImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createVmImage': grpc.unary_unary_rpc_method_handler(
                    servicer.createVmImage,
                    request_deserializer=lcmservice__pb2.CreateVmImageRequest.FromString,
                    response_serializer=lcmservice__pb2.CreateVmImageResponse.SerializeToString,
            ),
            'queryVmImage': grpc.unary_unary_rpc_method_handler(
                    servicer.queryVmImage,
                    request_deserializer=lcmservice__pb2.QueryVmImageRequest.FromString,
                    response_serializer=lcmservice__pb2.QueryVmImageResponse.SerializeToString,
            ),
            'deleteVmImage': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteVmImage,
                    request_deserializer=lcmservice__pb2.DeleteVmImageRequest.FromString,
                    response_serializer=lcmservice__pb2.DeleteVmImageResponse.SerializeToString,
            ),
            'downloadVmImage': grpc.unary_stream_rpc_method_handler(
                    servicer.downloadVmImage,
                    request_deserializer=lcmservice__pb2.DownloadVmImageRequest.FromString,
                    response_serializer=lcmservice__pb2.DownloadVmImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lcmservice.VmImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VmImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createVmImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.VmImage/createVmImage',
            lcmservice__pb2.CreateVmImageRequest.SerializeToString,
            lcmservice__pb2.CreateVmImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryVmImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.VmImage/queryVmImage',
            lcmservice__pb2.QueryVmImageRequest.SerializeToString,
            lcmservice__pb2.QueryVmImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteVmImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lcmservice.VmImage/deleteVmImage',
            lcmservice__pb2.DeleteVmImageRequest.SerializeToString,
            lcmservice__pb2.DeleteVmImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def downloadVmImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/lcmservice.VmImage/downloadVmImage',
            lcmservice__pb2.DownloadVmImageRequest.SerializeToString,
            lcmservice__pb2.DownloadVmImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
