// Copyright 2020 Huawei Technologies Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: lcmservice.proto

package lcmservice

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InstantiateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*InstantiateRequest_AccessToken
	//	*InstantiateRequest_AppInstanceId
	//	*InstantiateRequest_HostIp
	//	*InstantiateRequest_Package
	Data isInstantiateRequest_Data `protobuf_oneof:"data"`
}

func (x *InstantiateRequest) Reset() {
	*x = InstantiateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstantiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateRequest) ProtoMessage() {}

func (x *InstantiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateRequest.ProtoReflect.Descriptor instead.
func (*InstantiateRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{0}
}

func (m *InstantiateRequest) GetData() isInstantiateRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *InstantiateRequest) GetAccessToken() string {
	if x, ok := x.GetData().(*InstantiateRequest_AccessToken); ok {
		return x.AccessToken
	}
	return ""
}

func (x *InstantiateRequest) GetAppInstanceId() string {
	if x, ok := x.GetData().(*InstantiateRequest_AppInstanceId); ok {
		return x.AppInstanceId
	}
	return ""
}

func (x *InstantiateRequest) GetHostIp() string {
	if x, ok := x.GetData().(*InstantiateRequest_HostIp); ok {
		return x.HostIp
	}
	return ""
}

func (x *InstantiateRequest) GetPackage() []byte {
	if x, ok := x.GetData().(*InstantiateRequest_Package); ok {
		return x.Package
	}
	return nil
}

type isInstantiateRequest_Data interface {
	isInstantiateRequest_Data()
}

type InstantiateRequest_AccessToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3,oneof"`
}

type InstantiateRequest_AppInstanceId struct {
	AppInstanceId string `protobuf:"bytes,2,opt,name=appInstanceId,proto3,oneof"`
}

type InstantiateRequest_HostIp struct {
	HostIp string `protobuf:"bytes,3,opt,name=hostIp,proto3,oneof"`
}

type InstantiateRequest_Package struct {
	Package []byte `protobuf:"bytes,4,opt,name=package,proto3,oneof"`
}

func (*InstantiateRequest_AccessToken) isInstantiateRequest_Data() {}

func (*InstantiateRequest_AppInstanceId) isInstantiateRequest_Data() {}

func (*InstantiateRequest_HostIp) isInstantiateRequest_Data() {}

func (*InstantiateRequest_Package) isInstantiateRequest_Data() {}

type InstantiateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InstantiateResponse) Reset() {
	*x = InstantiateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstantiateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateResponse) ProtoMessage() {}

func (x *InstantiateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateResponse.ProtoReflect.Descriptor instead.
func (*InstantiateResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{1}
}

func (x *InstantiateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TerminateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken   string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AppInstanceId string `protobuf:"bytes,2,opt,name=appInstanceId,proto3" json:"appInstanceId,omitempty"`
	HostIp        string `protobuf:"bytes,3,opt,name=hostIp,proto3" json:"hostIp,omitempty"`
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TerminateRequest) GetAppInstanceId() string {
	if x != nil {
		return x.AppInstanceId
	}
	return ""
}

func (x *TerminateRequest) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken   string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AppInstanceId string `protobuf:"bytes,2,opt,name=appInstanceId,proto3" json:"appInstanceId,omitempty"`
	HostIp        string `protobuf:"bytes,3,opt,name=hostIp,proto3" json:"hostIp,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *QueryRequest) GetAppInstanceId() string {
	if x != nil {
		return x.AppInstanceId
	}
	return ""
}

func (x *QueryRequest) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type UploadCfgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*UploadCfgRequest_AccessToken
	//	*UploadCfgRequest_HostIp
	//	*UploadCfgRequest_ConfigFile
	Data isUploadCfgRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadCfgRequest) Reset() {
	*x = UploadCfgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCfgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCfgRequest) ProtoMessage() {}

func (x *UploadCfgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCfgRequest.ProtoReflect.Descriptor instead.
func (*UploadCfgRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{6}
}

func (m *UploadCfgRequest) GetData() isUploadCfgRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadCfgRequest) GetAccessToken() string {
	if x, ok := x.GetData().(*UploadCfgRequest_AccessToken); ok {
		return x.AccessToken
	}
	return ""
}

func (x *UploadCfgRequest) GetHostIp() string {
	if x, ok := x.GetData().(*UploadCfgRequest_HostIp); ok {
		return x.HostIp
	}
	return ""
}

func (x *UploadCfgRequest) GetConfigFile() []byte {
	if x, ok := x.GetData().(*UploadCfgRequest_ConfigFile); ok {
		return x.ConfigFile
	}
	return nil
}

type isUploadCfgRequest_Data interface {
	isUploadCfgRequest_Data()
}

type UploadCfgRequest_AccessToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3,oneof"`
}

type UploadCfgRequest_HostIp struct {
	HostIp string `protobuf:"bytes,2,opt,name=hostIp,proto3,oneof"`
}

type UploadCfgRequest_ConfigFile struct {
	ConfigFile []byte `protobuf:"bytes,3,opt,name=configFile,proto3,oneof"`
}

func (*UploadCfgRequest_AccessToken) isUploadCfgRequest_Data() {}

func (*UploadCfgRequest_HostIp) isUploadCfgRequest_Data() {}

func (*UploadCfgRequest_ConfigFile) isUploadCfgRequest_Data() {}

type UploadCfgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UploadCfgResponse) Reset() {
	*x = UploadCfgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCfgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCfgResponse) ProtoMessage() {}

func (x *UploadCfgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCfgResponse.ProtoReflect.Descriptor instead.
func (*UploadCfgResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{7}
}

func (x *UploadCfgResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveCfgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	HostIp      string `protobuf:"bytes,2,opt,name=hostIp,proto3" json:"hostIp,omitempty"`
}

func (x *RemoveCfgRequest) Reset() {
	*x = RemoveCfgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCfgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCfgRequest) ProtoMessage() {}

func (x *RemoveCfgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCfgRequest.ProtoReflect.Descriptor instead.
func (*RemoveCfgRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveCfgRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RemoveCfgRequest) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type RemoveCfgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveCfgResponse) Reset() {
	*x = RemoveCfgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCfgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCfgResponse) ProtoMessage() {}

func (x *RemoveCfgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCfgResponse.ProtoReflect.Descriptor instead.
func (*RemoveCfgResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveCfgResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryKPIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	HostIp      string `protobuf:"bytes,2,opt,name=hostIp,proto3" json:"hostIp,omitempty"`
}

func (x *QueryKPIRequest) Reset() {
	*x = QueryKPIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryKPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKPIRequest) ProtoMessage() {}

func (x *QueryKPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKPIRequest.ProtoReflect.Descriptor instead.
func (*QueryKPIRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{10}
}

func (x *QueryKPIRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *QueryKPIRequest) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type QueryKPIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *QueryKPIResponse) Reset() {
	*x = QueryKPIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryKPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKPIResponse) ProtoMessage() {}

func (x *QueryKPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKPIResponse.ProtoReflect.Descriptor instead.
func (*QueryKPIResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{11}
}

func (x *QueryKPIResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type QueryMepCapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	HostIp      string `protobuf:"bytes,2,opt,name=hostIp,proto3" json:"hostIp,omitempty"`
}

func (x *QueryMepCapRequest) Reset() {
	*x = QueryMepCapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMepCapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMepCapRequest) ProtoMessage() {}

func (x *QueryMepCapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMepCapRequest.ProtoReflect.Descriptor instead.
func (*QueryMepCapRequest) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{12}
}

func (x *QueryMepCapRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *QueryMepCapRequest) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type QueryMepCapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *QueryMepCapResponse) Reset() {
	*x = QueryMepCapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lcmservice_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMepCapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMepCapResponse) ProtoMessage() {}

func (x *QueryMepCapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcmservice_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMepCapResponse.ProtoReflect.Descriptor instead.
func (*QueryMepCapResponse) Descriptor() ([]byte, []int) {
	return file_lcmservice_proto_rawDescGZIP(), []int{13}
}

func (x *QueryMepCapResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_lcmservice_proto protoreflect.FileDescriptor

var file_lcmservice_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x9e,
	0x01, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x0d, 0x61, 0x70, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x12, 0x1a, 0x0a, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x2d, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x72,
	0x0a, 0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x70, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f,
	0x73, 0x74, 0x49, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74,
	0x49, 0x70, 0x22, 0x2b, 0x0a, 0x11, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x6e, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x22,
	0x2b, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7a, 0x0a, 0x10,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x66, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x12, 0x20,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x66, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4c, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43,
	0x66, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x6f, 0x73, 0x74, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73,
	0x74, 0x49, 0x70, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x66, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x4b, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4b, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x22, 0x2e, 0x0a,
	0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4b, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4e, 0x0a,
	0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x70, 0x43, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x22, 0x31, 0x0a,
	0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x70, 0x43, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xaa, 0x04, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x4c, 0x43, 0x4d, 0x12, 0x52, 0x0a, 0x0b, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x6c, 0x63, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x63, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x4a, 0x0a, 0x09, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6c,
	0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x63, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x6c, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x6c, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x2e, 0x6c, 0x63,
	0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x66, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x63, 0x6d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x66, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x2e, 0x6c, 0x63, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x66,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x63, 0x6d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x66, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x08, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x4b, 0x50, 0x49, 0x12, 0x1b, 0x2e, 0x6c, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4b, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4b, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x59, 0x0a, 0x14, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x70, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x6c, 0x63, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x70,
	0x43, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x63, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x70,
	0x43, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lcmservice_proto_rawDescOnce sync.Once
	file_lcmservice_proto_rawDescData = file_lcmservice_proto_rawDesc
)

func file_lcmservice_proto_rawDescGZIP() []byte {
	file_lcmservice_proto_rawDescOnce.Do(func() {
		file_lcmservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_lcmservice_proto_rawDescData)
	})
	return file_lcmservice_proto_rawDescData
}

var file_lcmservice_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_lcmservice_proto_goTypes = []interface{}{
	(*InstantiateRequest)(nil),  // 0: lcmservice.InstantiateRequest
	(*InstantiateResponse)(nil), // 1: lcmservice.InstantiateResponse
	(*TerminateRequest)(nil),    // 2: lcmservice.TerminateRequest
	(*TerminateResponse)(nil),   // 3: lcmservice.TerminateResponse
	(*QueryRequest)(nil),        // 4: lcmservice.QueryRequest
	(*QueryResponse)(nil),       // 5: lcmservice.QueryResponse
	(*UploadCfgRequest)(nil),    // 6: lcmservice.UploadCfgRequest
	(*UploadCfgResponse)(nil),   // 7: lcmservice.UploadCfgResponse
	(*RemoveCfgRequest)(nil),    // 8: lcmservice.RemoveCfgRequest
	(*RemoveCfgResponse)(nil),   // 9: lcmservice.RemoveCfgResponse
	(*QueryKPIRequest)(nil),     // 10: lcmservice.QueryKPIRequest
	(*QueryKPIResponse)(nil),    // 11: lcmservice.QueryKPIResponse
	(*QueryMepCapRequest)(nil),  // 12: lcmservice.QueryMepCapRequest
	(*QueryMepCapResponse)(nil), // 13: lcmservice.QueryMepCapResponse
}
var file_lcmservice_proto_depIdxs = []int32{
	0,  // 0: lcmservice.AppLCM.instantiate:input_type -> lcmservice.InstantiateRequest
	2,  // 1: lcmservice.AppLCM.terminate:input_type -> lcmservice.TerminateRequest
	4,  // 2: lcmservice.AppLCM.query:input_type -> lcmservice.QueryRequest
	6,  // 3: lcmservice.AppLCM.uploadConfig:input_type -> lcmservice.UploadCfgRequest
	8,  // 4: lcmservice.AppLCM.removeConfig:input_type -> lcmservice.RemoveCfgRequest
	10, // 5: lcmservice.AppLCM.queryKPI:input_type -> lcmservice.QueryKPIRequest
	12, // 6: lcmservice.AppLCM.queryMepCapabilities:input_type -> lcmservice.QueryMepCapRequest
	1,  // 7: lcmservice.AppLCM.instantiate:output_type -> lcmservice.InstantiateResponse
	3,  // 8: lcmservice.AppLCM.terminate:output_type -> lcmservice.TerminateResponse
	5,  // 9: lcmservice.AppLCM.query:output_type -> lcmservice.QueryResponse
	7,  // 10: lcmservice.AppLCM.uploadConfig:output_type -> lcmservice.UploadCfgResponse
	9,  // 11: lcmservice.AppLCM.removeConfig:output_type -> lcmservice.RemoveCfgResponse
	11, // 12: lcmservice.AppLCM.queryKPI:output_type -> lcmservice.QueryKPIResponse
	13, // 13: lcmservice.AppLCM.queryMepCapabilities:output_type -> lcmservice.QueryMepCapResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_lcmservice_proto_init() }
func file_lcmservice_proto_init() {
	if File_lcmservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lcmservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstantiateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstantiateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCfgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCfgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCfgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCfgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryKPIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryKPIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMepCapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lcmservice_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMepCapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lcmservice_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*InstantiateRequest_AccessToken)(nil),
		(*InstantiateRequest_AppInstanceId)(nil),
		(*InstantiateRequest_HostIp)(nil),
		(*InstantiateRequest_Package)(nil),
	}
	file_lcmservice_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*UploadCfgRequest_AccessToken)(nil),
		(*UploadCfgRequest_HostIp)(nil),
		(*UploadCfgRequest_ConfigFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lcmservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lcmservice_proto_goTypes,
		DependencyIndexes: file_lcmservice_proto_depIdxs,
		MessageInfos:      file_lcmservice_proto_msgTypes,
	}.Build()
	File_lcmservice_proto = out.File
	file_lcmservice_proto_rawDesc = nil
	file_lcmservice_proto_goTypes = nil
	file_lcmservice_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppLCMClient is the client API for AppLCM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppLCMClient interface {
	Instantiate(ctx context.Context, opts ...grpc.CallOption) (AppLCM_InstantiateClient, error)
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	UploadConfig(ctx context.Context, in *UploadCfgRequest, opts ...grpc.CallOption) (*UploadCfgResponse, error)
	RemoveConfig(ctx context.Context, in *RemoveCfgRequest, opts ...grpc.CallOption) (*RemoveCfgResponse, error)
	QueryKPI(ctx context.Context, in *QueryKPIRequest, opts ...grpc.CallOption) (*QueryKPIResponse, error)
	QueryMepCapabilities(ctx context.Context, in *QueryMepCapRequest, opts ...grpc.CallOption) (*QueryMepCapResponse, error)
}

type appLCMClient struct {
	cc grpc.ClientConnInterface
}

func NewAppLCMClient(cc grpc.ClientConnInterface) AppLCMClient {
	return &appLCMClient{cc}
}

func (c *appLCMClient) Instantiate(ctx context.Context, opts ...grpc.CallOption) (AppLCM_InstantiateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AppLCM_serviceDesc.Streams[0], "/lcmservice.AppLCM/instantiate", opts...)
	if err != nil {
		return nil, err
	}
	x := &appLCMInstantiateClient{stream}
	return x, nil
}

type AppLCM_InstantiateClient interface {
	Send(*InstantiateRequest) error
	CloseAndRecv() (*InstantiateResponse, error)
	grpc.ClientStream
}

type appLCMInstantiateClient struct {
	grpc.ClientStream
}

func (x *appLCMInstantiateClient) Send(m *InstantiateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *appLCMInstantiateClient) CloseAndRecv() (*InstantiateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InstantiateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *appLCMClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, "/lcmservice.AppLCM/terminate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLCMClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/lcmservice.AppLCM/query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLCMClient) UploadConfig(ctx context.Context, in *UploadCfgRequest, opts ...grpc.CallOption) (*UploadCfgResponse, error) {
	out := new(UploadCfgResponse)
	err := c.cc.Invoke(ctx, "/lcmservice.AppLCM/uploadConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLCMClient) RemoveConfig(ctx context.Context, in *RemoveCfgRequest, opts ...grpc.CallOption) (*RemoveCfgResponse, error) {
	out := new(RemoveCfgResponse)
	err := c.cc.Invoke(ctx, "/lcmservice.AppLCM/removeConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLCMClient) QueryKPI(ctx context.Context, in *QueryKPIRequest, opts ...grpc.CallOption) (*QueryKPIResponse, error) {
	out := new(QueryKPIResponse)
	err := c.cc.Invoke(ctx, "/lcmservice.AppLCM/queryKPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLCMClient) QueryMepCapabilities(ctx context.Context, in *QueryMepCapRequest, opts ...grpc.CallOption) (*QueryMepCapResponse, error) {
	out := new(QueryMepCapResponse)
	err := c.cc.Invoke(ctx, "/lcmservice.AppLCM/queryMepCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppLCMServer is the server API for AppLCM service.
type AppLCMServer interface {
	Instantiate(AppLCM_InstantiateServer) error
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	UploadConfig(context.Context, *UploadCfgRequest) (*UploadCfgResponse, error)
	RemoveConfig(context.Context, *RemoveCfgRequest) (*RemoveCfgResponse, error)
	QueryKPI(context.Context, *QueryKPIRequest) (*QueryKPIResponse, error)
	QueryMepCapabilities(context.Context, *QueryMepCapRequest) (*QueryMepCapResponse, error)
}

// UnimplementedAppLCMServer can be embedded to have forward compatible implementations.
type UnimplementedAppLCMServer struct {
}

func (*UnimplementedAppLCMServer) Instantiate(AppLCM_InstantiateServer) error {
	return status.Errorf(codes.Unimplemented, "method Instantiate not implemented")
}
func (*UnimplementedAppLCMServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Terminate not implemented")
}
func (*UnimplementedAppLCMServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedAppLCMServer) UploadConfig(context.Context, *UploadCfgRequest) (*UploadCfgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadConfig not implemented")
}
func (*UnimplementedAppLCMServer) RemoveConfig(context.Context, *RemoveCfgRequest) (*RemoveCfgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveConfig not implemented")
}
func (*UnimplementedAppLCMServer) QueryKPI(context.Context, *QueryKPIRequest) (*QueryKPIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryKPI not implemented")
}
func (*UnimplementedAppLCMServer) QueryMepCapabilities(context.Context, *QueryMepCapRequest) (*QueryMepCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMepCapabilities not implemented")
}

func RegisterAppLCMServer(s *grpc.Server, srv AppLCMServer) {
	s.RegisterService(&_AppLCM_serviceDesc, srv)
}

func _AppLCM_Instantiate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppLCMServer).Instantiate(&appLCMInstantiateServer{stream})
}

type AppLCM_InstantiateServer interface {
	SendAndClose(*InstantiateResponse) error
	Recv() (*InstantiateRequest, error)
	grpc.ServerStream
}

type appLCMInstantiateServer struct {
	grpc.ServerStream
}

func (x *appLCMInstantiateServer) SendAndClose(m *InstantiateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *appLCMInstantiateServer) Recv() (*InstantiateRequest, error) {
	m := new(InstantiateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AppLCM_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLCMServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcmservice.AppLCM/Terminate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLCMServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLCM_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLCMServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcmservice.AppLCM/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLCMServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLCM_UploadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCfgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLCMServer).UploadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcmservice.AppLCM/UploadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLCMServer).UploadConfig(ctx, req.(*UploadCfgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLCM_RemoveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCfgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLCMServer).RemoveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcmservice.AppLCM/RemoveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLCMServer).RemoveConfig(ctx, req.(*RemoveCfgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLCM_QueryKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLCMServer).QueryKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcmservice.AppLCM/QueryKPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLCMServer).QueryKPI(ctx, req.(*QueryKPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLCM_QueryMepCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMepCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLCMServer).QueryMepCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcmservice.AppLCM/QueryMepCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLCMServer).QueryMepCapabilities(ctx, req.(*QueryMepCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppLCM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lcmservice.AppLCM",
	HandlerType: (*AppLCMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "terminate",
			Handler:    _AppLCM_Terminate_Handler,
		},
		{
			MethodName: "query",
			Handler:    _AppLCM_Query_Handler,
		},
		{
			MethodName: "uploadConfig",
			Handler:    _AppLCM_UploadConfig_Handler,
		},
		{
			MethodName: "removeConfig",
			Handler:    _AppLCM_RemoveConfig_Handler,
		},
		{
			MethodName: "queryKPI",
			Handler:    _AppLCM_QueryKPI_Handler,
		},
		{
			MethodName: "queryMepCapabilities",
			Handler:    _AppLCM_QueryMepCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "instantiate",
			Handler:       _AppLCM_Instantiate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "lcmservice.proto",
}
